backend:
  name: github
  repo: sajclarke/cms-test

media_folder: media_folder

collections:
  - name: post
    label: Post
    folder: pages
    create: true
    fields:
      - {name: title, label: Title}
      - {name: body, label: Body, widget: markdown}